### PR TITLE
Update for 2017.3 API changes

### PR DESCRIPTION
**Pull request by hurricup**

### CODE REVIEW

**Comment by samwoods1** [comment]
@hurricup Where is org.jetbrains.plugins.ruby.gem.RubyGemExecutionContext coming from?  I installed the 2017.3 IntelliJ EAP, and the updated Ruby plugin 2017.3.20171023 and I still don't see it.

**Comment by hurricup** [comment]
Check rubymine please, ruby plugin may be outdated.

**Comment by samwoods1** [comment]
Thanks! I pushed a new version to plugins.jetbrains.com with these changes.

**Comment by hurricup** [comment]
You are welcome. Could you please also adjust Untill version in repository for previous releases? 
Like:

image

Thanks!

**Pull request merged**
